---

- name: Install docker-machine-driver-kvm
  get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
    dest: /usr/local/bin/docker-machine-driver-kvm
    owner: root
    group: root
    mode: 0755
  become: yes

- block:
    - name: Get latest release of minishift
      uri:
        url: https://api.github.com/repos/minishift/minishift/releases/latest
      register: minishift_latest_release

    - name: Set minishift_version to latest release
      set_fact:
        minishift_version: "{{ minishift_latest_release.json.tag_name }}"
  when: minishift_version == 'latest'

- name: Check for minishift binary
  stat:
    path: "{{ minishift_binary_path }}"
  register: stat_minishift_binary

- block:
    - name: Get installed minishift version
      command: "{{ minishift_binary_path }} version"
      register: get_minishift_version
      changed_when: no

    - name: Set installed_minishift_version
      set_fact:
        installed_minishift_version: '{{ get_minishift_version.stdout | regex_search("(v[\d\.]+)") }}'
  when: stat_minishift_binary.stat.exists

- block:
    - name: Create temporary download directory
      tempfile:
        state: directory
      register: minishift_download_dir
      changed_when: no

    - name: Download minishift
      unarchive:
        src: "{{ minishift_download_url }}"
        dest: "{{ minishift_download_dir.path }}"
        remote_src: yes

    - name: Install minishift
      copy:
        src: "{{ minishift_download_dir.path }}/{{ minishift_archive_filename | regex_replace('.tgz$', '') }}/minishift"
        dest: "{{ minishift_binary_path }}"
        owner: root
        group: root
        mode: 0755
        remote_src: yes
      become: yes
  always:
    - name: Delete temporary download directory
      file:
        path: "{{ minishift_download_dir.path }}"
        state: absent
      changed_when: no
  when: minishift_version != installed_minishift_version

